server:
  port: 8086
spring:
#  profiles:
#    active:
#      - consumer
      
  dubbo:
#####################################################扫描注解的包###############################################################
#    base-package: com.reger.test.consumer
#####################################################扫描注解的包###############################################################

    application:
      name: demo-consumer
#      owner: laolei
#      architecture:
#      compiler: javassist
#      environment: develop
#      logger: slf4j
#      organization: reger
#      version: 0.0.1
      
#####################################################消费者默认配置###############################################################
    consumer:                    # 公用的消费者配置
      lazy: true                 #
      timeout: 1000              # 可选 性能调优 远程服务调用超时时间(毫秒) 1.0.16以上版本
      check: false                # 可选 服务治理 启动时检查提供者是否存在，true报错，false忽略 1.0.16以上版本
      retries: 20                # 可选 性能调优 远程服务调用重试次数，不包括第一次调用，不需要重试请设为0 1.0.16以上版本
#      registry: test                # 可选 配置关联 向指定注册中心注册，在多个注册中心时使用，值为spring.dubbo.registry.的id属性，多个注册中心ID用逗号分隔，如果不想将该服务注册到任何registry，可将值设为N/A 2.0.5以上版本
#      actives: 0                # 可选 性能调优 每服务消费者每服务每方法最大并发调用数 2.0.5以上版本
#      filter: consumerFilter     # 可选 性能调优 服务消费方远程调用过程拦截器名称，多个名称用逗号分隔 2.0.5以上版本
#      async: false              # 可选 性能调优 是否缺省异步执行，不可靠异步，只是忽略返回值，不阻塞执行线程 2.0.0以上版本
#      cache:                    # 可选 服务治理 以调用参数为key，缓存返回结果，可选：lru, threadlocal, jcache等 Dubbo2.1.0及其以上版本支持
#      cluster: failover         # 可选 性能调优 集群方式，可选：failover/failfast/failsafe/failback/forking 2.0.5以上版本
#      connections: 100          # 可选 性能调优 每个服务对每个提供者的最大连接数，rmi、http、hessian等短连接协议支持此配置，dubbo协议长连接不支持此配置 1.0.16以上版本
#      generic: false            # 可选 服务治理 是否缺省泛化接口，如果为泛化接口，将返回GenericService 2.0.0以上版本
#      init: false               # 可选 性能调优 是否在afterPropertiesSet()时饥饿初始化引用，否则等到有人注入或引用该实例时再初始化。 2.0.10以上版本
#      layer:                    # 可选 服务治理 服务调用者所在的分层。如：biz、dao、intl:web、china:acton。 2.0.7以上版本
#      listener:                 # 可选 性能调优 服务消费方引用服务监听器名称，多个名称用逗号分隔 2.0.5以上版本
#      loadbalance: random       # 可选 性能调优 负载均衡策略，可选值：random,roundrobin,leastactive，分别表示：随机，轮循，最少活跃调用 1.0.16以上版本
#      owner:                    # 可选 服务治理 调用服务负责人，用于服务治理，请填写负责人公司邮箱前缀 2.0.5以上版本
#      proxy: javassist          # 可选 性能调优 生成动态代理方式，可选：jdk/javassist 2.0.5以上版本
#      retries: 2                # 可选 性能调优 远程服务调用重试次数，不包括第一次调用，不需要重试请设为0 1.0.16以上版本
#      validation:               # 可选 服务治理 是否启用JSR303标准注解验证，如果启用，将对方法参数上的注解进行校验 Dubbo2.1.0及其以上版本支持
#####################################################消费者默认配置###############################################################
      
        
#####################################################消费者配置###############################################################
#    references:
#      - actives: 
#        async:
#        cache:
#        check:
#        client: 
#        cluster: 
#        connections: 
#        filter: 
#        generic:
#        group: 
#        id: 
#        init:
#        interface: 
#        layer: 
#        listener: 
#        loadbalance: 
#        mock:
#        owner: 
#        protocol: 
#        proxy:
#        registry: 
#        retries: 
#        stub:
#        timeout: 
#        url: 
#        validation:
#        version: 
#        
####################################################消费者配置###############################################################
    registry:               # 应用注册中心配置项
      id: test
      protocol: zookeeper   # 必填 服务发现 注册中心支持的协议 包括 dubbo,multicast,zookeeper,redis 默认是zookeeper
      address: 127.0.0.1    # 必填 服务发现 注册中心服务器地址，如果地址没有端口缺省为9090，同一集群内的多个地址用逗号分隔，如：ip:port,ip:port，不同集群的注册中心，请配置多个spring.dubbo.registry.标签 1.0.16以上版本
      port: 2181            # 可选 服务发现 注册中心缺省端口，当address没有带端口时使用此端口做为缺省值 2.0.0以上版本
      client: zkclient      # 可选 服务发现 注册中心支持的客户端， zookeeper 支持客户端包括 curator和zkclient,如果不配置，默认使用zkclient
#      register: true        # 可选 服务治理 是否向此注册中心注册服务，如果设为false，将只订阅，不注册 2.0.5以上版本
#      session: 60000        # 可选 性能调优 注册中心会话超时时间(毫秒)，用于检测提供者非正常断线后的脏数据，比如用心跳检测的实现，此时间就是心跳间隔，不同注册中心实现不一样。 2.1.0以上版本
#      check: false          # 可选 服务治理 服务是否动态注册，如果设为false，注册后将显示后disable状态，需人工启用，并且服务提供者停止时，也不会自动取消册，需人工禁用。 2.0.5以上版本
#      dynamic: true         # 可选 服务治理 服务是否动态注册，如果设为false，注册后将显示后disable状态，需人工启用，并且服务提供者停止时，也不会自动取消册，需人工禁用。 2.0.5以上版本
#      file: regcache.log    # 可选 服务治理 使用文件缓存注册中心地址列表及服务提供者列表，应用重启时将基于此文件恢复，注意：两个注册中心不能使用同一文件存储 2.0.0以上版本
#      username:             # 可选 服务治理 登录注册中心用户名，如果注册中心不需要验证可不填 2.0.0以上版本
#      password:             # 可选 服务治理 登录注册中心密码，如果注册中心不需要验证可不填 2.0.0以上版本
#      subscribe:            # 可选 服务治理 是否向此注册中心订阅服务，如果设为false，将只注册，不订阅 2.0.5以上版本
#      timeout:              # 可选 性能调优 注册中心请求超时时间(毫秒) 2.0.0以上版本
#      wait: 0               # 可选 性能调优 停止时等待通知完成时间(毫秒) 2.0.0以上版本
#      transport: netty      # 可选 性能调优 网络传输方式，可选mina,netty 2.0.0以上版本
#      id:                   # 可选 配置关联 注册中心引用BeanId，可以在<dubbo:service registry="">或<dubbo:reference registry="">中引用此ID 1.0.16以上版本

    registrys:               # 多个应用注册中心时配置项
      - id: test1
        protocol: zookeeper   # 必填 服务发现 注册中心支持的协议 包括 dubbo,multicast,zookeeper,redis 默认是zookeeper
        address: 127.0.0.1    # 必填 服务发现 注册中心服务器地址，如果地址没有端口缺省为9090，同一集群内的多个地址用逗号分隔，如：ip:port,ip:port，不同集群的注册中心，请配置多个spring.dubbo.registry.标签 1.0.16以上版本
        port: 2181            # 可选 服务发现 注册中心缺省端口，当address没有带端口时使用此端口做为缺省值 2.0.0以上版本
        client: zkclient      # 可选 服务发现 注册中心支持的客户端， zookeeper 支持客户端包括 curator和zkclient,如果不配置，默认使用zkclient

      - id: test2
        protocol: zookeeper   # 必填 服务发现 注册中心支持的协议 包括 dubbo,multicast,zookeeper,redis 默认是zookeeper
        address: 127.0.0.1    # 必填 服务发现 注册中心服务器地址，如果地址没有端口缺省为9090，同一集群内的多个地址用逗号分隔，如：ip:port,ip:port，不同集群的注册中心，请配置多个spring.dubbo.registry.标签 1.0.16以上版本
        port: 2181            # 可选 服务发现 注册中心缺省端口，当address没有带端口时使用此端口做为缺省值 2.0.0以上版本
        client: zkclient      # 可选 服务发现 注册中心支持的客户端， zookeeper 支持客户端包括 curator和zkclient,如果不配置，默认使用zkclient

      - id: test3
        protocol: zookeeper   # 必填 服务发现 注册中心支持的协议 包括 dubbo,multicast,zookeeper,redis 默认是zookeeper
        address: 127.0.0.1    # 必填 服务发现 注册中心服务器地址，如果地址没有端口缺省为9090，同一集群内的多个地址用逗号分隔，如：ip:port,ip:port，不同集群的注册中心，请配置多个spring.dubbo.registry.标签 1.0.16以上版本
        port: 2181            # 可选 服务发现 注册中心缺省端口，当address没有带端口时使用此端口做为缺省值 2.0.0以上版本
        client: zkclient      # 可选 服务发现 注册中心支持的客户端， zookeeper 支持客户端包括 curator和zkclient,如果不配置，默认使用zkclient
#####################################################注册中心###############################################################

#####################################################监控中心###############################################################
#
#    monitor:                # 监控服务
#      address: N/A          # 可选 服务治理 直连监控中心服务器地址，address="10.20.130.230:12080" 1.0.16以上版本
#      protocol: dubbo       # 可选 服务治理 监控中心协议，如果为protocol="registry"，表示从注册中心发现监控中心地址，否则直连监控中心。 2.0.9以上版本
#################################################监控中心###############################################################

#####################################################模块信息###############################################################
#
#    module:                 # 应用模块定义
#      name:                 # 必填 服务治理 当前模块名称，用于注册中心计算模块间依赖关系 2.2.0以上版本
#      organization:         # 可选 服务治理 组织名称(BU或部门)，用于注册中心区分服务来源，此配置项建议不要使用autoconfig，直接写死在配置中，比如china,intl,itu,crm,asc,dw,aliexpress等 2.2.0以上版本
#      owner:                # 可选 服务治理 模块负责人，用于服务治理，请填写负责人公司邮箱前缀 2.2.0以上版本
#      version:              # 可选 服务治理 当前模块的版本 2.2.0以上版本
#####################################################模块信息###############################################################

#####################################################协议信息###############################################################

    protocol:               # 默认的应用协议栈
      id: dubbo
      name: dubbo           # 必填 性能调优 协议名称 2.0.5以上版本
      serialization: hessian2 #可选 性能调优 协议序列化方式，当协议支持多种序列化方式时使用，比如：dubbo协议的dubbo,hessian2,java,compactedjava，以及http协议的json等 2.0.5以上版本
#      accepts: 0            # 可选 性能调优 服务提供方最大可接受连接数 2.0.5以上版本
#      accesslog: false      # 可选 服务治理 设为true，将向logger中输出访问日志，也可填写访问日志文件路径，直接把访问日志输出到指定文件 2.0.5以上版本
#      buffer: 8192          # 可选 性能调优 网络读写缓冲区大小 2.0.5以上版本
#      charset: UTF-8        # 可选 性能调优 序列化编码 2.0.5以上版本
#      client: netty         # 可选 性能调优 协议的客户端实现类型，比如：dubbo协议的mina,netty等 2.0.5以上版本
#      codec: dubbo          # 可选 性能调优 协议编码方式 2.0.5以上版本
#      contextpath:          # 可选 服务治理 2.0.6以上版本
#      dispatcher: all       # 可选 性能调优 协议的消息派发方式，用于指定线程模型，比如：dubbo协议的all, direct, message, execution, connection等 2.1.0以上版本
#      heartbeat: 0          # 可选 性能调优 心跳间隔，对于长连接，当物理层断开时，比如拔网线，TCP的FIN消息来不及发送，对方收不到断开事件，此时需要心跳来帮助检查连接是否已断开 2.0.10以上版本
#      host:                 # 可选 服务发现 -服务主机名，多网卡选择或指定VIP及域名时使用，为空则自动查找本机IP，-建议不要配置，让Dubbo自动获取本机IP 2.0.5以上版本
#      id: dubbo             # 可选 配置关联 协议BeanId，可以在<dubbo:service protocol="">中引用此ID，如果ID不填，缺省和name属性值一样，重复则在name后加序号。 2.0.5以上版本
#      iothreads:            # 可选 性能调优 io线程池大小(固定大小) 2.0.5以上版本
#      path:                 # 可选 服务发现 提供者上下文路径，为服务path的前缀 2.0.5以上版本
#      payload: 88388608     # 可选 性能调优 请求及响应数据包大小限制，单位：字节 2.0.5以上版本
#      port:                 # 可选 服务发现不输入或者输入0，将自动在53600~53688之间生产一个  服务端口  2.0.5以上版本 ，
#      queues: 0             # 可选 性能调优 线程池队列大小，当线程池满时，排队等待执行的队列大小，建议不要设置，当线程程池时应立即失败，重试其它服务提供机器，而不是排队，除非有特殊需求。 2.0.5以上版本
#      register: true        # 可选 服务治理 该协议的服务是否注册到注册中心 2.0.8以上版本
#      server:               # 可选 性能调优 协议的服务器端实现类型，比如：dubbo协议的mina,netty等，http协议的jetty,servlet等 2.0.5以上版本
#      telnet:               # 可选 服务治理 所支持的telnet命令，多个命令用逗号分隔 2.0.5以上版本
#      threadpool: fixed     # 可选 性能调优 线程池类型，可选：fixed/cached 2.0.5以上版本
#      threads: 100          # 可选 性能调优 服务线程池大小(固定大小) 2.0.5以上版本
#      transporter: netty    # 可选 性能调优 协议的服务端和客户端实现类型，比如：dubbo协议的mina,netty等，可以分拆为server和client配置 2.0.5以上版本

  #  如果需要配置多个协议可以使用如下方式
    protocols:
      - id: dubbo-jvm
        name: dubbo
        serialization: nativejava
      - id: dubbo-hessian
        name: dubbo
        serialization: hessian2
      - id: dubbo-fastjson
        name: dubbo
        serialization: fastjson
      - id: dubbo-dubbo
        name: dubbo
        serialization: dubbo
      - id: rmi
        name: rmi
      - id: http
        name: http
      - id: hessian
        name: hessian
      - id: thrift
        name: thrift
      - id: webservice
        name: webservice
####################################################协议信息###############################################################
